<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>

<strong class="choose-option">Bitte wählen Sie</strong>
<br><br>
<div class="login-toggler">
    <div class="field custom">
        <input id="login-check" class="login-check" name="login" type="radio" checked="checked"/>
        <label data-content="#login-1" class="label" for="login-check"><b>Ich habe ein Benutzerkonto</b></label>
    </div>
    <div id="login-1" class="block block-customer-login toggle-content">
        <div class="block-content" aria-labelledby="block-customer-login-heading">

            <form class="form form-login"
                  action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
                  method="post"
                  id="login-form"
                  data-mage-init='{"validation":{}}'>
                <?= $block->getBlockHtml('formkey') ?>
                <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                    <div class="field email required">
                        <label class="label" for="email"><span><?= $block->escapeHtml(__('E-Mail Adresse')) ?></span></label>
                        <div class="control">
                            <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text validate-email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-validate="{required:true, 'validate-email':true}">
                        </div>
                    </div>
                    <div class="field password required">
                        <label for="pass" class="label"><span><?= $block->escapeHtml(__('Passwort')) ?></span></label>
                        <div class="control">
                            <input name="login[password]" type="password" placeholder="zeigen" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                        </div>
                    </div>
                    <?= $block->getChildHtml('form_additional_info') ?>
                    <button type="submit" class="action login primary weiter" name="send" id="send2"><span><?= $block->escapeHtml(__('weiter')) ?></span></button>
                    <a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Passwort vergessen?')) ?></span></a>
                </fieldset>
            </form>
        </div>
        <div class="line"></div>
    </div>
</div>
<br>


