<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php if ($crumbs && is_array($crumbs)) : ?>
<div class="breadcrumbs-wrapper">
    <div class="breadcrumbs">
        <ul class="items">
            <a class="back-button" href="javascript: history.go(-1)"><span>zurück</span></a>
            <li class="item item-desc">Sie befinden sich hier:</li>
            <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                <li class="item <?= /* @escapeNotVerified */ $crumbName ?>">
                    <?php if ($crumbInfo['link']) : ?>
                        <a href="<?= /* @escapeNotVerified */ $crumbInfo['link'] ?>" title="<?= $block->escapeHtml($crumbInfo['title']) ?>"><?= $block->escapeHtml($crumbInfo['label']) ?></a>
                    <?php elseif ($crumbInfo['last']) : ?>
                        <strong><?= $block->escapeHtml($crumbInfo['label']) ?></strong>
                    <?php else: ?>
                        <?= $block->escapeHtml($crumbInfo['label']) ?>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <div class="breadcrumbs-info">
        <div class="breadcrumbs-phone"><span class="icon-content">04102 804 5045</span></div>
        <div class="breadcrumbs-email">
            <a href="mailto:kundenservice@kroschke.de" target="_top" title="Kroschke" class="icon-content">kundenservice@kroschke.de</a>
        </div>
    </div>
</div>
<?php endif; ?>

