<?php
/**
 * @var $block Magento\Framework\View\Element\Template
 */
?>

<div class="add-to-cart-tooltip">
    <p><span class="item-qty"></span> Artikel wurde zum Warenkorb hinzugefügt.</p>
    <a href="#" class="modal-close primary action"><?= __('Weiter einkaufen') ?></a>
    <a href="<?= $block->getUrl('checkout') ?>" class="primary action"><?= __('Zur Kasse') ?></a>
</div>

<script>
    require(['jquery', 'Magento_Ui/js/modal/modal', 'mage/translate', 'mage/url'], function ($, modal, $t, url) {
        var options = {
            type: 'popup',
            responsive: true,
            innerScroll: true,
            modalClass: 'tooltip-modal'
        };

        var $modal = $('.add-to-cart-tooltip').modal(options);

        $(document).on('ajax:addToCart', function (e, sku, form, res) {
            //find qty and update
            $modal.find('.item-qty').text($('#qty').val());

            $modal.modal('openModal');
        });
        $('.add-to-cart-tooltip').find('.modal-close').click(function () {
            $modal.modal('closeModal');
        });
    });
</script>